# production:
#   adapter: postgresql
#   database: investy
#   pool: 5

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: investy